### ISSUE TITLE
Allow players to disable the radar without also disabling the proximity pings

### ISSUE THREAD

**Issue by Protonull** [MrJeremyFisher/CombatRadar#15]
Since [CivVoxelMap](https://github.com/Protonull/CivVoxelMap) has a legal radar, I have two radars on my screen at all times. I would like to disable CombatRadar's radar, but doing so also disables the proximity pings of people coming in and out of render distance. It would be nice if these were two separate features that could be enabled separately.

**Comment by MrJeremyFisher** [comment]
Good idea. Not sure when I'll be able to get around to this.
